Lesson timer
spartakusQ/Rails-First-App pull request #19
Opened 2018-11-16 19:31 UTC by spartakusQ

Задание "Таймер"

2018-11-17 18:12 UTC, BubuntuClu requested changes

2018-11-17 18:12 UTC, BubuntuClu commented on app/assets/javascripts/utilites/timer.js
> +  var seconds = Math.floor(seconds % 3600 % 60);
у тебя аргумент функции имеет такое же имя

2018-11-17 18:12 UTC, BubuntuClu commented on app/models/passing_test.rb
> +    return if test.timer.nil?
делай отступ после `return` строки

2018-11-17 18:12 UTC, BubuntuClu commented on app/models/passing_test.rb
> +    time_left = (test.timer || return) - (Time.now.to_i - created_at.to_i)
а что за `|| return`? как это работать должно?

2018-11-17 18:12 UTC, BubuntuClu commented on app/assets/javascripts/utilites/timer.js
> +  timer.classList.remove('timer');
после истечения времени надо вывести сообщение что время вышло и надо переместить пользователя на страницу результатов. иначе он может просто продолжать проходить тест

2018-11-17 18:12 UTC, BubuntuClu commented on app/assets/javascripts/utilites/timer.js
> +  var timer = document.querySelector('.timer');
если обновить страницу, то таймер начнет отсчет сначала, такого быть не должно.

2018-11-19 09:55 UTC, BubuntuClu commented on app/assets/javascripts/utilites/timer.js
> +    location.replace("http://localhost:3000/")
можно через `window.location = newUrl;`
но этот метод надо вызывать. сейчас у тебя нет вызова

2018-11-24 17:31 UTC, BubuntuClu commented on app/controllers/passing_tests_controller.rb
> +    @passing_test.accept!(params[:answer_ids]) if answer_ids.any?
а как это работает? ты создал массив пустой, потом сразу же проверяешь есть ли в нем что-то

2018-11-25 23:56 UTC, psylone approved these changes

2018-11-25 23:56 UTC, psylone commented on app/models/passing_test.rb
> +  def remaining_seconds
Поскольку это публичный метод, значит его можно вызвать. Если у теста не будет таймера, возникнет исключение.

2018-11-25 23:56 UTC, psylone commented on db/schema.rb
> +    t.bigint "test_end_time"
Как используются эти поля?

2018-11-25 23:56 UTC, psylone commented on db/schema.rb
> +    t.bigint "test_time_left"
Как используется это поле?

2018-11-26 19:57 UTC, merged